name: Publish

on:
  push:
    tags:
      - v*.*.*

env:
  CARGO_TERM_COLOR: always

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check version
        uses: tcurdt/action-verify-version-cargo@master

  audit:
    name: Audit
    runs-on: ubuntu-latest
    needs: [check-version]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/audit

  build_and_test:
    strategy:
      matrix:
        rust-version: [stable]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: [check-version]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_and_test
        id: build_and_test
        with:
          rust-version: ${{ matrix.rust-version }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [check-version, audit, build_and_test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish
        # We can use --no-verify here, because they are verified already by the
        # build_and_test job(s).
        run: cargo publish --verbose --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --no-verify

