name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check version
        uses: tcurdt/action-verify-version-cargo@master

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/audit

  msrv:
    runs-on: ubuntu-latest
    outputs:
      msrv: "${{ steps.msrv.outputs.msrv }}"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/msrv
        id: msrv

  test:
    needs: [msrv]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          rust-version: "${{ needs.msrv.outputs.msrv }}"

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [check-version, audit, test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish
        # We can use --no-verify here, because they are verified already by the
        # build_and_test job(s).
        run: cargo publish --verbose --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --no-verify
